# Generated by Django 2.0.7 on 2018-07-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='CPF',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='Nome',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='Tel',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
