# Generated by Django 2.0.7 on 2018-07-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180706_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='CPF',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='product',
            name='Tel',
            field=models.CharField(max_length=20),
        ),
    ]
