# Generated by Django 2.0.7 on 2018-07-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='idade',
            field=models.IntegerField(max_length=2, null=True),
        ),
    ]
