# Generated by Django 2.0.7 on 2018-07-10 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20180709_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='CPF',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Tel',
            field=models.CharField(max_length=9, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='product',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='product',
            name='idade',
            field=models.IntegerField(null=True, verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nasc',
            field=models.DateTimeField(null=True, verbose_name='Data de Nasc'),
        ),
    ]
