# Generated by Django 2.0.7 on 2018-07-10 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20180709_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='CPF',
            field=models.CharField(blank=True, max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='nasc',
            field=models.DateField(null=True, verbose_name='Data de Nasc'),
        ),
    ]
