# Generated by Django 2.0.7 on 2018-07-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20180709_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='CPF',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
